### ISSUE TITLE
[FR]: Add ability to upload all files (attachments) in path relative to file

### ISSUE THREAD

**Issue by dneez** [Enveloppe/obsidian-enveloppe#376]
### Issue validation

- [x] I checked the issue to prevent duplicate

### What solution do you want to see ?

I would like to be able to upload all attachments (files) in the folder where md file resides.
For example with following structure:
```
Blog
  PostName
    PostName.md
  images
    image1.jpg
    illustration2.png
    ...
```
Currently it will only upload .md file and whatever is linked inside file. My theme uses a lot of images in frontmatter.
I would like anything in `images` folder to be uploaded as well.

I know that I could use front matter key to specify which attachments to upload, but my frontmatter is hierarchical and it looks like plugin can't handle it.
Example of frontmatter:
```
---
share: true
galleryImages1:
  - image: images/image1.jpg
    caption: Caption1
  - image: images/image2.JPG
  - image: images/image3.JPG
    caption: Capture3
---
```

### Describe the alternative you've considered

I have considered to change handling of frontmatter in plugin. In the [logic](https://github.com/Enveloppe/obsidian-enveloppe/blob/f3c2712265dfa2a64bce737fd5f84ec23024cf74/src/GitHub/files.ts#L548), that checks forntmatter for key you assume forntmatter has one dimension, hence usage of `const fieldValue = dataviewMetadata[field];`

Maybe the frontmatter object could be flattened to one dimension, something like this:
Given my example frontmatter
```
---
share: true
galleryImages1:
  - image: images/image1.jpg
    caption: Caption1
  - image: images/image2.JPG
  - image: images/image3.JPG
    caption: Capture3
---
```

Resulting object could be
```
{
  'share': true,
  'galleryImages1.[0].image': 'images/image1.jpg',
  'galleryImages1.[0].caption': 'Caption1',
  'galleryImages1.[1].image': 'images/image2.jpg',
  'galleryImages1.[2].image': 'images/image3.jpg',
  'galleryImages1.[2].caption': 'Caption3',
}
```

Then we could also match key by RegEx. Example: `/galleryImages\d+\.\[\d+\]\.image/`

### OS

Windows

### Plugin version

7.5.2

### Obsidian version & debug log

```bash session
Obsidian: 1.8.1
```
